sudo: false
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
    - PACKAGE=vcontrold
  matrix:
    - SDK_URL=https://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/barrier_breaker/14.07/kirkwood/generic/OpenWrt-SDK-kirkwood-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/barrier_breaker/14.07/lantiq/xway/OpenWrt-SDK-lantiq-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
    - SDK_URL=https://downloads.openwrt.org/barrier_breaker/14.07/ramips/rt305x/OpenWrt-SDK-ramips-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xjf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/files package/$PACKAGE/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- ./scripts/feeds update packages >/dev/null
- ./scripts/feeds install -d m libxml2
- make V=s
- find $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/
- find . -name *.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: jJBKTduvxWOc+0ANQJ3o+j+Pb71S2k2BbqqhyYvWZM40H8jW4euy4/NaLWYf5oNnF5YslmUtvK53m98sBpvu63sHNQ3vK/aoZEGMozFne76Z+PkgL3SZCr8ia/Un+IwEQ0C50FPGBa/osy583r2ajca0rKLlTN0M8zCTACCKm3w=
  skip_cleanup: true
  file_glob: true
  file: $TRAVIS_BUILD_DIR/*.ipk
  on:
    tags: true
    all_branches: true
